### ISSUE TITLE
After crash only restricted telemetry 

### ISSUE THREAD

**Issue by Signellox** [iNavFlight/LuaTelemetry#354]
Taranis X9D with  FrSky R9Telemetry Receiver and a Matek Systems F405-WING (New) STM32F405 Flight Controller Built-in OSD .

 Taranis  detects only RxBt and RSSI Sensor. (?)
All other functions seems to be ok.

S Port is conected and activated.

I reinstalled the INAV software but its not completly clear because there are four posibilities.
MATEK 405 did not work, MAtek 405SE, MATEK 405 SERVOS, MATEK 405OSD.
I installed MATEK 405 OSD.

It would be nice to get some help on this topic.

**Comment by teckel12** [comment]
@Signellox This would be an issue with setting up your flight controller (either INAV or physical connection) not with the LuaTelemetry script.

The two sensors you're seeing are from the receiver. So either you don't have the flight controller physically connected to the receiver correctly or you don't have INAV setup correctly. Please look for help via the INAV docs or on Telegram for community support (see the INAV repo for the Telegram link).

**Comment by Signellox** [comment]
Thanks!




On Wed, Oct 16, 2019 at 6:23 PM +0200, "Tim Eckel" <notifications@github.com> wrote:












Closed #354.
