### ISSUE TITLE
How to access settings menu on Jumper T-Lite?

### ISSUE THREAD

**Issue by avsaase** [iNavFlight/LuaTelemetry#466]
### Describe your question
The title. As far as I can see there is no way to access the menu and change the settings on this transmitter.

### To reproduce
System and model buttons don't work. Neither do the stick commands used on the newer transmitters.

### Expected behavior
It should be possible to change the settings.

### Additional context
I would also be perfectly happy to change some text files to adjust the settings. `\SCRIPTS\TELEMETRY\iNav\cfg\readme.txt` suggests the configuration files for each model are stored in that folder, but the folder is otherwise empty.

**Comment by Sekilsgs2** [comment]
This need some modifications to iNav.lua from src folder - 
in 511 line change line
`elseif event == MENU then`
to 
`elseif event == MENU or event == EVT_DOWN_LONG then`
Than need recompile this edited script in opentx simualtor and next place compilled script to Radio.
And after you can go to settings with pushing down buttong long

**Comment by avsaase** [comment]
Still needs to be implemented.

**Comment by julianschweizer** [comment]
I added a PR https://github.com/teckel12/LuaTelemetry/pull/476 credits go to Sekilsgs2
Thanks!

**Comment by avsaase** [comment]
not stale

**Comment by avsaase** [comment]
not stale

**Comment by axelfenner** [comment]
solve ths issue....
