### ISSUE TITLE
Inav Lua Telemetry weird colors on widget

### ISSUE THREAD

**Issue by iPamp** [iNavFlight/LuaTelemetry#490]
### Describe the bug
The telemetry widget has weird colors, no brown ground, no blue background, no fonts info. Please see the image: https://i.postimg.cc/pdpXQFFS/weird-colors.jpg

### To reproduce
Edge tx latest version, lua telemetry script latest version, there is no steps to reproduce the weird colors, I just installed it and never worked with normal colors.

### Expected behavior
Have normal colors, normal fonts, brown ground on horizon level, blue background on entire screen.

### Screenshots
Here is the screen
https://i.postimg.cc/pdpXQFFS/weird-colors.jpg

### Radio and model settings
tx16s markii latest edge tx for today.

### Additional context
Thank you all for helping me in advance. ❤

**Comment by Taboaco** [comment]
> ### Describe the bug
> The telemetry widget has weird colors, no brown ground, no blue background, no fonts info. Please see the image: https://i.postimg.cc/pdpXQFFS/weird-colors.jpg
> 
> ### To reproduce
> Edge tx latest version, lua telemetry script latest version, there is no steps to reproduce the weird colors, I just installed it and never worked with normal colors.
> 
> ### Expected behavior
> Have normal colors, normal fonts, brown ground on horizon level, blue background on entire screen.
> 
> ### Screenshots
> Here is the screen https://i.postimg.cc/pdpXQFFS/weird-colors.jpg
> 
> ### Radio and model settings
> tx16s markii latest edge tx for today.
> 
> ### Additional context
> Thank you all for helping me in advance. ❤

I’m having the exact same problem, edited the theme and got the brown under the horizon but no text, they are the same color as the background! Tried all combinations!
Any news?
Thanks

**Comment by iPamp** [comment]
> 

ya man, i've found a fix.  just download the real latest version of lua telemetry from this link https://github.com/iNavFlight/OpenTX-Telemetry-Widget/releases

ensure that your controller has the "telemetry info/sensors" working. Any future questions, i'm here 😁
